# Generated by Django 4.2.3 on 2023-07-19 19:13

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('orderList', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TodoListModel',
            fields=[
                ('listid', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('listname', models.CharField(max_length=1000)),
                ('deadline', models.DateField()),
                ('todocount', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Owner', to='todoApp.owner')),
            ],
            options={
                'unique_together': {('listid', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todoid', models.IntegerField(default=0)),
                ('newtodo', models.TextField()),
                ('done', models.BooleanField()),
                ('ownertodos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todolist', to='todoApp.todolistmodel')),
            ],
            options={
                'unique_together': {('newtodo', 'ownertodos')},
            },
        ),
    ]
