# Generated by Django 4.2.3 on 2023-07-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='id',
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='todoid',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
