# Generated by Django 4.2.3 on 2023-07-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoApp", "0002_remove_todoitem_id_alter_todoitem_todoid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="owner",
            name="orderList",
        ),
        migrations.AlterField(
            model_name="todoitem",
            name="todoid",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
